Remove unnecessary Modeshape code/constants.
fcrepo/fcrepo pull request #1767
Opened 2020-10-07 16:41 UTC by whikloj

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3444

# What does this Pull Request do?
Removes a bunch of static constants that related to Modeshape and its requirements. This PR should not have any effect on the way Fedora currently operates.

# How should this be tested?

Fedora still does Fedora.

# Interested parties
@fcrepo/committers

2020-10-07 22:28 UTC, awoods requested changes
Looks good. I suspect we can also remove:
- https://github.com/fcrepo/fcrepo/blob/main/fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java#L112-L113
- https://github.com/fcrepo/fcrepo/blob/main/fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java#L187-L191

2020-10-09 23:59 UTC, whikloj commented
I am experiencing some test failures that seem odd. A build fails with
```
[ERROR] Failures: 
[ERROR]   FedoraVersioningIT.testAddAndRetrieveVersion:964 Should not find the updated title in historic version
[ERROR]   FedoraVersioningIT.testCreateVersionOfBinaryDescription:927 Property added after memento created must not appear
[INFO] 
[ERROR] Tests run: 410, Failures: 2, Errors: 0, Skipped: 86
```

If I run just each test, they seem to pass. If I build the entire project with `-DskipTests` and execute from outside it seems to work.

2020-10-13 12:11 UTC, pwinckles approved these changes

2020-10-13 13:18 UTC, awoods approved these changes

2020-10-13 13:19 UTC, merged