More integration tests
fcrepo/fcrepo pull request #1809
Opened 2020-11-18 04:50 UTC by whikloj

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3223

# What does this Pull Request do?
Another iteration on re-enabling integration tests.

# How should this be tested?

Ensure the changes made to the tests (or application) are correct.

In this exciting episode:
1. When adding a blank node to a resource's graph, we no longer allow you to directly access the blank node as a URI (I was not aware you could ever do that). Instead we just check that the blank node is part of the resource's graph.
1. We ensure that GET -> PUT interactions omit server managed triples.
1. We change the expectations for binary and binary description ETags. They used to be separate and so changing one would not affect the other. They now a linked together.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @fcrepo/committers

2020-11-18 23:34 UTC, awoods requested changes
Thanks, @whikloj .

2020-11-18 23:34 UTC, awoods commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
> -        get6.addHeader("If-None-Match", binaryEtag1);
Could we keep this request with the change to `If-Match`?

2020-11-18 23:34 UTC, awoods commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
> -        get7.addHeader("If-Modified-Since", binaryLastModed1);
Could we keep this request with the change to `If-Unmodified-Since`?

2020-11-19 17:04 UTC, whikloj commented
Somewhat related but I (and @pwinckles ) have experienced test failures due to 1 second differences in the FedoraVersioningIT. I have made a change to allow a small variance in the Memento URIs. I hope this is ok.

2020-11-19 18:07 UTC, awoods approved these changes

2020-11-19 18:08 UTC, merged