Consider context path when interpreting relative URIs in RDF
fcrepo/fcrepo pull request #1847
Opened 2021-01-12 17:10 UTC by whikloj

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3598

# What does this Pull Request do?
When a relative URI (ie. `</rest/someObject>`) is used in a RDF document it gets parsed against the baseUri and ends up as `info:/rest/someObject`. This is fine if using the internal jetty as there is no additional context path, but when deployed to Tomcat under (say `fcrepo6`) you get incorrect internal IDs.

This now takes the context path into consideration.

# How should this be tested?

1. Before the PR, deploy F6 to Tomcat under whatever context (ie `fcrepo6` for example).
1. Try to PUT a body using a valid relative URI.
     ```
     curl -i -ufedoraAdmin:fedoraAdmin -XPUT -H"Content-type: text/turtle" -d "<> <http://example.org/related> </fcrepo6/rest/object>" http://localhost:8080/fcrepo6/rest/testObject
     ```
1. Get the new object and see that the `/fcrepo6/rest/object` is not correctly converted and appears as `info:/fcrepo6/rest/object`
1. Pull in and build this PR.
1. Try the above PUT statement again with a new resource.
      ```
     curl -i -ufedoraAdmin:fedoraAdmin -XPUT -H"Content-type: text/turtle" -d "<> <http://example.org/related> </fcrepo6/rest/object>" http://localhost:8080/fcrepo6/rest/anotherObject
     ```
1. Get this object and see that `/fcrepo6/rest/object` now is converted to `http://localhost:8080/fcrepo6/rest/object`.
1. This should also work under any context and under the jetty container with just `/rest`

# Interested parties
Tag (@ mention) interested parties or, if unsure, @fcrepo/committers

2021-01-15 18:03 UTC, awoods requested changes
General note: the following produces a peculiar result:
```
echo "<> <http://example.com/related> <info://test1/child4>" | curl -i -ufedoraAdmin:fedoraAdmin -XPUT -H "Content-Type: text/turtle" --data-binary @- http://localhost:8080/f6/rest/test1
```
My Tomcat/Fedora is deployed at `/f6`, but that is not important here.

2021-01-18 15:52 UTC, whikloj commented on fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
> +    @Context protected ServletContext context;
It was part of a previous attempt just using the Context. I'll move it back

2021-01-18 15:53 UTC, whikloj commented on fcrepo-http-api/src/main/java/org/fcrepo/http/api/responses/StreamingBaseHtmlProvider.java
> +    private String contextPath = "";
How about instead I just pull the paths in the identifierConverter() method without the external string.
```java
    private HttpIdentifierConverter identifierConverter() {
        if (identifierConverter == null) {
            final UriBuilder uriBuilder =
                    uriInfo.getBaseUriBuilder().clone().path(FedoraLdp.class);
            final String contextPath = request.getContextPath() + request.getServletPath();
            identifierConverter = new HttpIdentifierConverter(uriBuilder, contextPath);
        }
        return identifierConverter;
    }
```

2021-01-18 15:59 UTC, whikloj commented on fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java
>              if (realpath.startsWith("/")) {
Not sure I understand why a while loop would make sense. If someone is using `//` is that not user error?

2021-01-18 16:38 UTC, whikloj commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
> +        final String body = "<> <http://example.org/related> </fcrepo/rest/test1> ; <http://example.org/related> " +
Sorry but what would the expected triple be in this case?

2021-01-22 17:12 UTC, whikloj commented
So to see how this works you need to check manually. What I did was run
```
> curl -i -ufedoraAdmin:fedoraAdmin -H"Content-type: text/turtle" -d "<> <http://example.org/related> </fcrepo/rest/test1> ; <http://example.org/related> 
</rest/test1> ; <http://example.org/related> <http://something.else/outThere> ;
<http://example.org/related> <test1> ." http://localhost:8080/rest -XPOST
```
and check the RDF in OCFL.
For `main` it is
```
> cat fcr-container.nt 
<info:fedora/521cfd58-cd00-48db-817a-7c1435ad32f2> <http://example.org/related> <http://something.else/outThere> .
<info:fedora/521cfd58-cd00-48db-817a-7c1435ad32f2> <http://example.org/related> <info:fedora/test1> .
<info:fedora/521cfd58-cd00-48db-817a-7c1435ad32f2> <http://example.org/related> <info:/fcrepo/rest/test1> .
```
For this PR it is
```
> cat fcr-container.nt 
<info:fedora/fca5241b-80a9-44b9-ac68-0dc45909f4aa> <http://example.org/related> <http://localhost:8080/fcrepo/rest/test1> .
<info:fedora/fca5241b-80a9-44b9-ac68-0dc45909f4aa> <http://example.org/related> <info:fedora/test1> .
<info:fedora/fca5241b-80a9-44b9-ac68-0dc45909f4aa> <http://example.org/related> <http://something.else/outThere> .
```

2021-01-22 19:42 UTC, awoods commented on fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraBaseResource.java
> +import static org.slf4j.LoggerFactory.getLogger;
It seems like all updates to this file could be usefully reverted from this PR.

2021-01-22 19:57 UTC, awoods requested changes

2021-01-22 19:57 UTC, awoods commented on fcrepo-http-commons/src/main/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverter.java
> +     * Create a new identifier converter within the given URI template and given context/servlet path.
This comment is out of date... given the most recent commit.

2021-01-22 19:57 UTC, awoods commented on fcrepo-http-commons/src/test/java/org/fcrepo/http/commons/api/rdf/HttpIdentifierConverterTest.java
> +import java.util.UUID;
It seems like this file can also be reverted from this PR.

2021-01-22 19:57 UTC, awoods commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
> +        final String body = "<> <http://example.org/related> </fcrepo/rest/test1> ; <http://example.org/related> " +
The [second example](https://tools.ietf.org/html/rfc3986#section-5.4.1) (`g`) would suggest the result be relative to the baseURI, not the repository root.

2021-01-22 19:57 UTC, awoods commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
> +        final String body = "<> <http://example.org/related> </fcrepo/rest/test1> ; <http://example.org/related> " +
For clarity in this test, it would likely be helpful to use `<test2>` instead of `<test1>`, again.

2021-01-23 02:55 UTC, whikloj commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
> +        final String body = "<> <http://example.org/related> </fcrepo/rest/test1> ; <http://example.org/related> " +
I thought like you did, but (after walking through Jena) I think the key is the second point under 5.2.3 Merge Paths
> return a string consisting of the reference's path component appended to all but the last segment of the base URI's path (i.e., excluding any characters after the **right-most** "/" in the base URI path, or excluding the entire base URI path if it does not contain any "/" characters).

So in our URI the right-most `/` is between `rest` and the UUID.

So looking at the example you referenced I actually think the key in that example is the original URI is
```
http://a/b/c/d
```
then you resolve `q` against it and get
```
http://a/b/c/q
```
not 
```
http://a/b/c/d/q
```
It goes back to the right-most slash deletes everything right of it from the base URI and then adds our relative path. 

I added a separate test that was the same but first created two levels above. So when resolving `<test3>` against `http://localhost:8080/rest/first/second/third` the result is `http://localhost:8080/rest/first/second/test3`

2021-01-25 16:49 UTC, awoods approved these changes

2021-01-25 17:05 UTC, merged