FCREPO-3410 - Indirect containers
fcrepo/fcrepo pull request #1848
Opened 2021-01-12 23:03 UTC by bbpennel

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3410
Also addresses:
https://jira.lyrasis.org/browse/FCREPO-3227
https://jira.lyrasis.org/browse/FCREPO-3468
https://jira.lyrasis.org/browse/FCREPO-3469

# What does this Pull Request do?
* Enables the creation of ldp:IndirectContainers
* IndirectContainers and proxies generate membership
* Re-enables and adds related integration tests
* Some refactoring of DirectContainer membership generation, since it overlapped considerably with indirect containers.

# How should this be tested?
In addition to the added tests, another good option is this branch of the PCDM in Action project, which updates it to work with fcrepo5 and 6:
https://github.com/bbpennel/ldp-pcdm/tree/fedora6

2021-01-13 18:48 UTC, awoods requested changes

2021-01-13 18:48 UTC, awoods commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java
> +    public void indirectContaineIsMemberOfMembershipHistory() throws Exception {
typo: "..ContaineIs.."

2021-01-13 18:48 UTC, awoods commented on fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/AbstractService.java
> +                            + " ldp:insertedContentRelation with a property as the object");
Would it be more clear to specify: "..with a URI property as the object"?

2021-01-13 21:38 UTC, bbpennel commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/FedoraLdpIT.java
> -@Ignore("Needs indirect containers - FCREPO-3410")
I was moving tests over from FedoraLdpIT to LDPContainerIT, and this one seemed redundant with `indirectContaineIsMemberOfMembershipHistory` which includes patching the properties of an IndirectContainer. I could add it back in though

2021-01-13 21:42 UTC, bbpennel commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java
> +        assertEquals(Status.CREATED.getStatusCode(), getStatus(putProxy));
I'd lean towards documentation. There aren't any requirements for proxies in the LDP spec as far as I can tell, and if we start doing enforcement of properties in proxies we could still end up in bad situations if an IndirectContainer is PATCH'ed to change its `insertedContentRelation` to a property that one of its children already has, which happens to have literals as their objects

2021-01-13 21:44 UTC, bbpennel commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java
> +    // Verify that bug involving committing delete transactions after modifying a proxy is fixed
No, it was just a bug I ran into during development of this PR which required a sequence of operations that made for a random seeming test, so I left that comment in there to indicate why the test was helpful. I can remove it

2021-01-13 22:06 UTC, awoods commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java
> +        assertEquals(Status.CREATED.getStatusCode(), getStatus(putProxy));
Jira created: https://jira.lyrasis.org/browse/FCREPO-3603

2021-01-13 22:07 UTC, awoods commented on fcrepo-http-api/src/test/java/org/fcrepo/integration/http/api/LDPContainerIT.java
> +    // Verify that bug involving committing delete transactions after modifying a proxy is fixed
Maybe update the comment so that it does not imply that there is an existing bug. That is what confused me: "Is there a bug"?

2021-01-14 14:47 UTC, awoods approved these changes

2021-01-14 15:03 UTC, awoods approved these changes

2021-01-14 15:04 UTC, merged