FCREPO-3752: Altering the external content URL does not update the binary metadata's last-modified date
fcrepo/fcrepo pull request #1933
Opened 2021-09-01 21:44 UTC by mikejritter

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3752

# What does this Pull Request do?

This updates the metadata handling for server managed properties to be applied to the binary headers rather than the binary description. This allows for the ManagedPropertiesService to resolve all managed properties from the binary.

# Changes

* Create a new operation for updating only the binary headers
* Create a new persister for updating the binary headers
* When updating a description, create two operations for managed and unmanaged properties
* Resolve managed properties from the Binary when possible

# How should this be tested?

There are two things to test here - the binary metadata being pulled from the correct source and that updates to server managed properties are done to the correct file.

## Binary Metadata

* Start fedora
* Create a binary
  ```
  curl -X PUT -H "Content-Type: text/plain" --data "somedata" -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=\"type\"" --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/test1 
  ```
* Get the metadata
  ```
  curl --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/binary/fcr:metadata
  ```
* Do a second put over top of the binary
  ```
  curl -X PUT -H "Content-Type: text/plain" --data "somemoredata" -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=\"type\"" --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/test1 
  ```
* Check that the metadata is updated properly

## Server Managed Properties

* Start fedora with relaxed properties mode
* Create a binary
  ```
  curl -X PUT -H "Content-Type: text/plain" --data "somedata" -H "Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel=\"type\"" --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/binary 
  ```
* Get the metadata for the binary and see that it matches what is the in the binary headers
  ```
  curl --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/binary/fcr:metadata
  ```
* Update the server managed properties on the binary
  ```
  curl -X PATCH --data "PREFIX fedora: <http://fedora.info/definitions/v4/repository#>
  INSERT {
      <> fedora:createdDate "2021-08-26T15:04:43.517Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
      fedora:lastModified "2021-08-26T15:04:43.517Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
  }
  WHERE  { }" -H "Content-Type: application/sparql-update" --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/descupdate/fcr:metadata 
  ```
* Get the metadata for the binary and see that it matches the update + what is the in the v2 binary headers
  ```
  curl --user fedoraAdmin:fedoraAdmin http://localhost:8080/rest/binary/fcr:metadata
  ```

# Interested parties
@fcrepo/committers

2021-09-03 13:22 UTC, pwinckles reviewed
Looks good!

A couple of minor comments. Additionally, can you add an itest to the `fcrepo-http-api` module?

I'll test it locally shortly, but my expectation is that it will work as expected.

2021-09-03 13:22 UTC, pwinckles commented on fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/UpdateRdfHeadersPersister.java
> +        log.info("persisting {} headers to {}", resourceId, session);
I think this should probably be debug. The other persisters are using debug, yeah?

2021-09-03 13:22 UTC, pwinckles commented on fcrepo-kernel-impl/src/main/java/org/fcrepo/kernel/impl/services/ReplacePropertiesServiceImpl.java
> +        tx.lockResource(operation.getResourceId());
I don't think you need this lock. I believe the resource is already locked on line 98

2021-09-07 19:14 UTC, mikejritter commented
@pwinckles Thanks for the review, I just got to it this morning. I added an integration test for checking the `LastModified` of the binary description after an update to a binary. The `FedoraRelaxedLdpIT` has one for server managed predicates so I opted not to add another for that.

2021-09-07 19:59 UTC, pwinckles approved these changes
👍

2021-09-08 13:31 UTC, whikloj requested changes
This seems 👍 just the one line that can be removed.

2021-09-08 17:49 UTC, whikloj approved these changes

2021-09-08 20:00 UTC, merged