Upgrade ocfl-java to 2.1.0, flyway to 9.x and try to fix some flappin…
fcrepo/fcrepo pull request #2083
Opened 2024-06-03 17:28 UTC by whikloj

…g tests

**JIRA Ticket**: https://fedora-repository.atlassian.net/browse/FCREPO-3936

# What does this Pull Request do?
Upgrades ocfl-java dependency to 2.1.0
Upgrades flywaydb dependency to 9.x
Tries to solve two flapping tests with using a single thread to get both actions within one second and to use await to wait a bit for changes.

# How should this be tested?

This really needs a test against S3, I took the defaults from the ocfl-java documentation so it is possible these are not ideal for our use case.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @fcrepo/committers

2024-06-03 17:32 UTC, whikloj commented
This PR will depend on https://github.com/fcrepo/fcrepo-storage-ocfl/pull/57 being merged first.

2024-06-06 23:03 UTC, mikejritter commented
@whikloj fyi it looks like the tests don't like the flyway `cleanDisabled` setting. Seems like it's coming from the `TestIsolationExecutionListener` calling `flyway.clean()`

2024-06-18 20:07 UTC, mikejritter requested changes
@whikloj I believe the only change that's actually needed is adding the credentials to the `s3CrtClient`. The dependency matching to ocfl-java would be nice but I didn't see any issues from it while testing.

Otherwise everything looks good and I was able to upload files > 8MB to S3 once the credentials were in place. I didn't look at the tests too in depth, they pass and there weren't big changes to them.

2024-06-19 16:02 UTC, whikloj commented on fcrepo-persistence-ocfl/src/main/java/org/fcrepo/persistence/ocfl/impl/OcflPersistenceConfig.java
> +                .checksumValidationEnabled(ocflPropsConfig.isOcflS3ChecksumEnabled())
I added in all 3 from the normal Async client to this CRT client.

2024-06-19 18:39 UTC, mikejritter approved these changes

2024-06-19 18:39 UTC, merged